#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '
{
  "*.{js,ts}": [
    "true || eslint --fix",
    "prettier --write"
  ],
  "*.{json,md,css,scss,html}": [
    "prettier --write"
  ]
}' | npm exec -- lint-staged --config -
